### ISSUE TITLE
DAL rework: Locationlog start_time isn't set when opening record via RADIUS request

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2694]
Performed a RADIUS request on Cisco::WLC configured to do webauth and entry was opened but start_time was left to 0

```
MariaDB [pf]> select * from locationlog\G
*************************** 1. row ***************************
                 id: 1
                mac: 94:db:c9:38:85:5b
             switch: 172.20.110.250
               port: 1
               vlan: 0
               role: registration
    connection_type: Wireless-802.11-NoEAP
connection_sub_type: NULL
     dot1x_username: 94dbc938855b
               ssid: ZAYME+MAJEW=LOVE
         start_time: 0000-00-00 00:00:00
           end_time: 0000-00-00 00:00:00
          switch_ip: 172.20.110.250
         switch_mac: 74:26:ac:2c:a4:90
 stripped_user_name: 94dbc938855b
              realm: null
         session_id: NULL
             ifDesc: NULL
```

**Comment by jrouzierinverse** [comment]
Fixed

**Comment by julsemaan** [comment]
I'm still getting that behavior, could you point the commit that fixes it so I make sure its in the build I'm using

**Comment by jrouzierinverse** [comment]
Fixed by f88cdb0fa168a0333bdea4adad3393404e421b4a

**Comment by julsemaan** [comment]
fix confirmed
