### ISSUE TITLE
DAL rework: auth_log attempted_at is left at 0

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2697]
Probably related to #2694 

Authenticating via SMS on the portal created the following record:
```
MariaDB [pf]> select * from auth_log\G
*************************** 1. row ***************************
          id: 1
process_name: httpd.portal
         mac: 94:db:c9:38:85:5b
         pid: 123457890
      status: incomplete
attempted_at: 0000-00-00 00:00:00
completed_at: NULL
      source: sms
```

**Comment by jrouzierinverse** [comment]
Fixed

**Comment by julsemaan** [comment]
Still happening right now, please point to the commit ID so I can confirm if its in our current build

**Comment by jrouzierinverse** [comment]
Fixed by f88cdb0fa168a0333bdea4adad3393404e421b4a

**Comment by julsemaan** [comment]
fix confirmed
