### ISSUE TITLE
DAL rework: Sponsor authentication is broken

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2705]
Probably related to #2698, the sponsor cannot login to sponsor the access if his device isn't managed already by PF.

It gets a rendering error because the DynamicRouting::Application failed to initialize.

Will revisit once #2698 gets fixed, so opening this just to keep track of it

To replicate:
* Grab a client device and do sponsor auth on the portal
* Grab a device not connected to your PF deployment and try to enable the sponsor link with it
* Contemplate error

If I create an ip4log entry for the sponsor device and create its node, then I'm able to perform the sponsor flow

**Comment by jrouzierinverse** [comment]
Fixed not sure by what

**Comment by julsemaan** [comment]
This is still not fixed

As described in the notes, the node used by the sponsor user must not exist in the DB for this to be replicated

**Comment by jrouzierinverse** [comment]
Fixed by 0b8e55143812f2cc1b0024fcffb772c5e6896307

**Comment by julsemaan** [comment]
fix confirmed
