### ISSUE TITLE
can't find saml_metadata.tt and SAML download error .... 

### ISSUE THREAD

**Issue by becchett** [inverse-inc/packetfence#3828]
Dear PF developers,
I'd like to report am issue about version 8.2.

The program was installed with yum in a centos with all the right 
requirements and after doing a basic configuration if I try to create an 
internal  SAML source I get this error displayed in the logs:

Dec  3 15:15:58 pfsrv admin_catalyst: httpd.admin(3156) ERROR: [mac:unknown] Couldn't render template "config/source/saml_metadata.tt: file error - config/source/saml_metadata.tt: not found" (Catalyst::View::TT::_rendering_error)
Dec  3 15:15:58 pfsrv admin_catalyst: httpd.admin(3156) ERROR: [mac:unknown] Couldn't render template "config/source/saml_metadata.tt: file error - config/source/saml_metadata.tt: not found" (Catalyst::finalize)

and in the browser I see this: "come back later"
To try to fix this error if I create a symbolic link:

cd /usr/local/pf/html/pfappserver/root/config/source/
ln -s type/SAML.tt saml_metadata.tt

now in the log files there is no more messages but in the browser I see
just a blank page.

Is it a bug that you can fix?
Thank you
Best Regards
Enrico

**Comment by julsemaan** [comment]
This should be fixed in the maintenance branch, you can apply it by running:

```
/usr/local/pf/addons/pf-maint.pl
```

**Comment by becchett** [comment]
Dear Julien,
this error didn't fix but is still present. 
Is there an Iverse or community developer who can reproduce this event ?
This is my log book 
- install a new mv Centos 7 x64_86 from iso with 8GB of RAM , 100GB HDD, 4 core and 
  two network interfaces
- Selinux and Firewalld disabled
- yum update

- /etc/NetworkManager/conf.d/99-no-dns.conf
[main]
dns=none

rpm -Uvh https://packetfence.org/downloads/PacketFence/RHEL7/x86_64/RPMS/packetfence-release-1.2-7.el7.noarch.rpm

yum install --enablerepo=packetfence packetfence

/usr/local/pf/addons/pf-maint.pl

after that from browser I config PF: https://10.0.0.34:1443/configurator

all of my screenshot are here 

as you can seen there is old error after download metadata:

https://owncloud.pg.infn.it/index.php/s/p19guu8548ntxvV

Dec  5 12:52:54 pfsrv admin_catalyst: httpd.admin(14645) ERROR: [mac:unknown] Couldn't render template "config/source/saml_metadata.tt: file error - config/source/saml_metadata.tt: not found" (Catalyst::View::TT::_rendering_error)

Are there any configuration erorrs or it'is a PF's Bug ?
Many thanks again
Best Regards
Enrico

**Comment by julsemaan** [comment]
Did you restart PacketFence after applying the maintenance ?

No need to reinstall from scratch, just apply the maintenance, restart the services (or reboot the machine) and try again

**Comment by nqb** [comment]
I have a fresh CentOS 7.6 with PF 8.2.1 installed. If necessary, I can try to reproduce.

**Comment by becchett** [comment]
> Did you restart PacketFence after applying the maintenance ?
> 
> No need to reinstall from scratch, just apply the maintenance, restart the services (or reboot the machine) and try again

yes

**Comment by becchett** [comment]
> I have a fresh CentOS 7.6 with PF 8.2.1 installed. If necessary, I can try to reproduce.

yes thanks !!!

**Comment by becchett** [comment]
> > Did you restart PacketFence after applying the maintenance ?
> > No need to reinstall from scratch, just apply the maintenance, restart the services (or reboot the machine) and try again
> 
> yes

PF ZEN 8.2.0 has the same problem .  Do you help it ?

**Comment by nqb** [comment]
First remark, regarding @becchett log: `config/source/saml_metadata.tt: not found`.
The path seems wrong:
```
# find /usr/local/pf -iname "*saml*"
[..]
./html/pfappserver/root/config/source/type/SAML.tt
```

**Comment by becchett** [comment]
> First remark, regarding @becchett log: `config/source/saml_metadata.tt: not found`.
> The path seems wrong:
> 
> ```
> # find /usr/local/pf -iname "*saml*"
> [..]
> ./html/pfappserver/root/config/source/type/SAML.tt
> ```

Yes I also have the same file but PF tell us about it doesn't exist , you've  seen this message.

Nov 30 10:47:23 pfsrv httpd_admin: httpd.admin(15072) ERROR: [mac:unknown] Caught exception in pfappserver::Controller::Config::Source->saml_metadata 
"Can't locate pf::Authentication::Source::SAMLSource in @INC (@INC contains: /usr/local/pf/conf /usr/local/fingerbank/lib /usr/local/pf/lib 
/usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . 

Do you already generate metadata from you instance ? Inside "Authorization"  field what do you choose ?  
Thanks 
Bye
Enrico

**Comment by julsemaan** [comment]
I don't think the template is the issue, it seems to be more the fact that the code is erroring out which tries to render a template with the action name.

@jrouzierinverse should have fixed that through #3722 which is in the maintenance so it would seem the fix would be incomplete.

Let me give it a try

**Comment by julsemaan** [comment]
actually, it seems that the fix that was done initially was then broken by this:
https://github.com/inverse-inc/packetfence/pull/3722/commits/9e7eb68a692e100a2cead89999e1c8f7ea36cad9#diff-80aa228d5fdf7eb7c965fe8c0d90a22eR159

I removed that line and the fix started working again.

Commit reference: 707cb4e7294747fa895bc6f25691dc078a99f134

**Comment by julsemaan** [comment]
Apply the maintenance again and restart the services and it should be all good
