### ISSUE TITLE
v9-gui: POTD sources should have rules 

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4326]
In old GUI, POTD source doesn't have authentication and administration rules because that didn't make sense.

In new GUI, it's possible to set such kind of rules.

**Comment by jrouzierinverse** [comment]
In the old GUI POTD can have rules.
However Billing/Blackhole/SAML/HTTP source cannot.

**Comment by jrouzierinverse** [comment]
I removed the rules in the OPTIONS for Billing/Blackhole/SAML/HTTP sources.

**Comment by satkunas** [comment]
Removed in https://github.com/inverse-inc/packetfence/commit/8a9916881dcfb6964a40789445f10e69e5f01b65

**Comment by nqb** [comment]
Issue still presents: I can't add rules for a POTD source under CentOS.

@jrouzierinverse, on current builds:
- Billing/Blackhole/SAML/HTTP source cannot in **old** GUI and **new** GUI
- POTD source cannot in **old** GUI and **new** GU

**Comment by julsemaan** [comment]
@fdurand will check the packaging issue

Debian only

**Comment by julsemaan** [comment]
@jrouzierinverse will investigate the formhandler issue

**Comment by jrouzierinverse** [comment]
Fixed by 9e9fe3c679220281efbcc2beb5c24efe9ae13223

**Comment by nqb** [comment]
Hello,

Now I got rules in **old** GUI for Debian and CentOS.

Still missing from **new** GUI for Debian and CentOS.
