### ISSUE TITLE
Old web admin: Can't add a login portal module

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#4505]
````
May 14 16:05:26 cluster1.zammit.corp admin_catalyst[5540]: httpd.admin(4835) ERROR: [mac:unknown] Couldn't render template "config/portal_module/view.tt: undef error - Can't use string ("") as an ARRAY ref while "strict refs" in use at /usr/share/perl5/vendor_perl/HTML/FormHandler/Widget/Field/Select.pm line 79.
                                                           " (Catalyst::View::TT::_rendering_error)
May 14 16:05:26 cluster1.zammit.corp admin_catalyst[5540]: httpd.admin(4835) ERROR: [mac:unknown] Couldn't render template "config/portal_module/view.tt: undef error - Can't use string ("") as an ARRAY ref while "strict refs" in use at /usr/share/perl5/vendor_perl/HTML/FormHandler/Widget/Field/Select.pm line 79.
                                                           " (Catalyst::finalize)
````

**Comment by satkunas** [comment]
Issue https://github.com/inverse-inc/packetfence/issues/4507 is waiting on this fix

**Comment by jrouzierinverse** [comment]
Fixed by 1a03e1464ed174960a5e1a73c521f74313107a96

**Comment by julsemaan** [comment]
Seems that its still missing in the latest devel even with @jrouzierinverse's fix

**Comment by julsemaan** [comment]
wrong issue
