### ISSUE TITLE
API: regdate not set when creating a node from web admin

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5036]
When you create a node from web admin, registration date is set to "0000-00-00 00:00:00" in DB. If you create a node using a CSV import, registration date is set to date and time of import.

Already the case in PF 9.2.

**To Reproduce**
1. Create a node from web admin
2. Check value of `regdate` in DB for node created at step 1

**Expected behavior**
Registration date should be set to date and time of creation.

**Comment by jrouzierinverse** [comment]
Are the nodes you created are registered or unregistered?

**Comment by nqb** [comment]
Registered.

**Comment by extrafu** [comment]
@jrouzierinverse Bump.

**Comment by jrouzierinverse** [comment]
Moving to 10.0 as it requires a discussion of what behavior do we want when creating and updating node from the API.
Don't want to change this behavior at the last minute.

**Comment by nqb** [comment]
@jrouzierinverse, can we speak about this change ?

**Comment by nqb** [comment]
We should be consistent in the way we update this field.

# Registered
Registration date should be set to date and time of creation.

# Registered -> Unregistered
Registration date should be to "0000-00-00 00:00:00"

**Comment by jrouzierinverse** [comment]
Fixed by 2f89ade96730f6af1cc4db319df4c9ef0a84cc26

**Comment by nqb** [comment]
This issue is not fixed from my point of view. If I use same steps to reproduce provided in issue description, I got same behaviour.
