### ISSUE TITLE
web admin: set_role send id of role in place of name

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5133]
**Describe the bug**
If you use `Actions` when you create a module under `Portal Modules` and assign a role, web admin send id of role in place of its name to API.

**To Reproduce**
1. Go in `Portal Modules`
1. Click on `New module` and create a new `Authentication::Login` module
1. Click on `Actions` and assign `guest` role to Role action
1. Save

In web browser console, you see:
```json
{"actions":[{"type":"set_role","value":"2"},{"type":"set_access_duration","value":"20m"}]
```
Value `2` is saved like this in `portal_modules.conf`

**Expected behavior**
Web admin should send name of role to API.

**Comment by rokkhan** [comment]
Same bug here using packetfence 9.3.0.

cat ../conf/roles.conf
[BYOD-Role]
max_nodes_per_pid=6

Mysql
MariaDB [pf]> select * from node_category;
+-------------+------------------+-------------------+----------------------------------------------+
| category_id | name             | max_nodes_per_pid | notes                                        |
+-------------+------------------+-------------------+----------------------------------------------+
|           1 | default          |                 0 | Placeholder role/category, feel free to edit |
|           2 | guest            |                 0 | Guests                                       |
|           3 | gaming           |                 0 | Gaming devices                               |
|           4 | voice            |                 0 | VoIP devices                                 |
|           5 | REJECT           |                 0 | Reject role (Used to block access)           |
|           8 | BYOD-Role |                 6 | NULL                                         |
+-------------+------------------+-------------------+----------------------------------------------+

When I create a new connection profile and an Authentication::Logiin portal module that assigns this new role through web admin, it assigns role category_id instead of role name.

[Byod-Auth]
source_id=
actions=**set_role(8)**,set_unregdate(2030-02-05)
fields_to_save=
custom_fields=
description=Byod-Auth
with_aup=0
signup_template=signin.html
pid_field=username
aup_template=aup_text.html
type=Authentication::Login

Feb  6 19:04:28 SLX00010808 packetfence_httpd.portal: httpd.portal(2960) INFO: [mac:40:a1:08:f5:c2:ac] Successfully authenticated user (captiveportal::PacketFence::DynamicRouting::Module::Authentication::Login::authenticate)
Feb  6 19:04:28 SLX00010808 packetfence_httpd.portal: httpd.portal(2960) INFO: [mac:40:a1:08:f5:c2:ac] Found source Metaldap in session. (Class::MOP::Class:::around)
Feb  6 19:04:28 SLX00010808 pfqueue: pfqueue(2604) INFO: [mac:unknown] Already did a person lookup for user (pf::lookup::person::lookup_person)
Feb  6 19:04:28 SLX00010808 packetfence_httpd.portal: httpd.portal(2960) INFO: [mac:40:a1:08:f5:c2:ac] User user has authenticated on the portal. (Class::MOP::Class:::after)
Feb  6 19:04:28 SLX00010808 packetfence_httpd.portal: httpd.portal(2960) WARN: [mac:40:a1:08:f5:c2:ac] **Specified role 8 doesn't exist for pid user** (MAC 40:a1:08:f5:c2:ac); assume maximum number of registered nodes is reached (pf::node::is_max_reg_nodes_reached)
Feb  6 19:04:28 SLX00010808 packetfence_httpd.portal: httpd.portal(2960) ERROR: [mac:40:a1:08:f5:c2:ac] max nodes per pid met or exceeded - registration of 40:a1:08:f5:c2:ac to user failed (pf::node::node_register)

**Comment by rokkhan** [comment]
Meanwhile it is solved. I did the trick to configure everything using the new admin and switching to the old admin to change only the role.

**Comment by garci66** [comment]
on 9.3 im also seeing something similar with the "AUP" flag. It gets saved and shown by the new GUI but its ignored functionally. Going into the old GUI lets you set/clear it and it takes effect. Im guessing (havent verified yet) that we're sending a 1/0 instead of true/false

**Comment by nqb** [comment]
Bug is still relevant on v10.0.9, if I follow steps to reproduce, I got this in `portal_modules.conf`:
```ini
[test]
aup_template=aup_text.html
with_aup=1
description=test
custom_fields=
type=Authentication::Login
source_id=
fields_to_save=
pid_field=username
signup_template=signin.html
actions=set_role(2),set_access_duration(3h)
```

**Comment by cgx** [comment]
@jrouzierinverse I guess we need to return `set_role_by_name` in the list of actions instead of simply `set_role`. Obviously it should not affect the `portal_modules.conf` file.

```bash
❯ /usr/local/pf/sbin/pfperl-api get -M OPTIONS '/api/v1/config/portal_module/default_login_policy' | jq '.meta.actions.item.properties.type.allowed[]|select(.value == "set_role")'
{
  "text": "Role",
  "value": "set_role"
}
```

**Comment by jrouzierinverse** [comment]
I sent set_role_by_name instead of set_role and it seems to have broken the viewing of portal modules containing an action with set_role_by_name.

**Comment by jrouzierinverse** [comment]
The branch where I did my changes is fix/portal_module_action_set_role_by_action.
The Admin GUI crashes whenever I use set_role_by_name as an action.
@cgx or @satkunas can you look into this?

**Comment by garci66** [comment]
Additionally, I wanted to point out that in the GUI it doesnt seem to be possible to use the "set_role_on_not_found" option for the portal modules. When setting an access duration it mentions it needs a "set_role" or "set_role_on_not_found" but the second option is only possible, at the moment, through direct editing of the config file.
