### ISSUE TITLE
Radius Filter regression

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5269]
**Describe the bug**
We lost some functionality in the radius filter.

1:
There is no way anymore to define the scope in radius (Control, proxy-request,reply,request...)

Something like:
```
[3:SSID|POC]
scope=packetfence.pre-proxy
merge_answer = yes
answer1 = proxy-request:User-Name => Robert!${radius_request.User-Name}
```
2:
Can't use the radius.request attribute in the condition, it's a hash

3:
RADIUS Status is always empty even if i choose something in.

4:
Can't choose anything in Answer, the list stay empty.

**Comment by jrouzierinverse** [comment]
1) Is there a complete list of radius scopes anywhere or would it be better to allow free form text?

2) @satkunas and I would need to figure out how to solve the issue with radius.{Attribute}
     I have an idea but we would need to look into the feasibility or we just allow free form text.

3) @satkunas can you look on why the radius_status cannot be selected

4) @satkunas can you look on why the answers are empty? 
     And we would need to allow them to edit it after the fact.

**Comment by fdurand** [comment]
1: 
Can be one of "request", "reply", "proxy-request", "proxy-reply", "coa", "disconnect", "session-state", or "control". As of Version 3, the <list> can be omitted, in which case "request" is assumed.

**Comment by satkunas** [comment]
> @satkunas and I would need to figure out how to solve the issue with radius.{Attribute}
I have an idea but we would need to look into the feasibility or we just allow free form text.

I'll add another field in the condition that will appear when 'radius_request' is selected - which will become a required field. This field will list the radius attributes to choose from. I'm not sure yet whether the field + radius_attribute will be appended together in the front-end, or if it will need to be done in the back-end.

For the 'answer', @jrouzierinverse will add a list of prefixes (including required: false to allow empty), and the front-end will return the chosen prefix for the backend to append with the radius_attribute.

**Comment by satkunas** [comment]
Support for prefixes added in https://github.com/inverse-inc/packetfence/commit/e9c5071d611606bcf32fa826cff179aa435aef73 https://github.com/inverse-inc/packetfence/commit/09d49c4266e2f1fa702761b0ed96c9d7ee407a05 https://github.com/inverse-inc/packetfence/commit/f35aa7bf543b9635e9357f4f5383c5b9f6ccc583 and https://github.com/inverse-inc/packetfence/commit/f4c91d68c8adf19996a213907f037a17b536f552

**Comment by satkunas** [comment]
> I'll add another field in the condition that will appear when 'radius_request' is selected - which will become a required field. This field will list the radius attributes to choose from. I'm not sure yet whether the field + radius_attribute will be appended together in the front-end, or if it will need to be done in the back-end.

Ideally the prefix will need to be added in the backend and sent via meta. There's too much work to change the behavior of the boolean builder to accommodate this change.

**Comment by satkunas** [comment]
> 1: There is no way anymore to define the scope in radius (Control, proxy-request,reply,request...)
> 2: Can't use the radius.request attribute in the condition, it's a hash

See my comment above

> 3: RADIUS Status is always empty even if i choose something in.

Fixed

> 4: Can't choose anything in Answer, the list stay empty.

Fixed

**Comment by jrouzierinverse** [comment]
All issues have been resolved, please verify.

**Comment by fdurand** [comment]
2: I think it will be better to remove radius_request from the list and be able to use it in the advanced mode. (or have a limited list of attributes).
There is too many attributes that can be listed.

**Comment by fdurand** [comment]
~~Also the attributes list should be a search list because i just have 3GPP... attributes in the list.~~
I was wrong, i am able to search.

Also i am not able to have the PacketFence-* radius attributes in the list.

**Comment by fdurand** [comment]
This:
![image](https://user-images.githubusercontent.com/1553962/78267585-21137200-74d5-11ea-9312-7229c700ba27.png)

Produce that in the configuration file:

```
[bromette]
status=enabled
answer.0=control:Acme-User-Class = HASH(0x11d582e8)
top_op=and
description=bromette
scopes=packetfence.authorize
radius_status=RLM_MODULE_OK
merge_answer=no
condition=mac == "00:11:22:33:44:55"
```

Note the HASH(0x11d582e8)

**Comment by jrouzierinverse** [comment]
This is fixed please try again.

**Comment by extrafu** [comment]
@fdurand All good?

**Comment by fdurand** [comment]
Nope

**Comment by fdurand** [comment]
@jrouzierinverse it still miss the PacketFence-* radius attributes in the list.
After that we will be good.

**Comment by jrouzierinverse** [comment]
done

**Comment by fdurand** [comment]
Installed the new dev package and still not see the PacketFence-* attributes.
