### ISSUE TITLE
vlan_filters.conf.defaults packetfence 10

### ISSUE THREAD

**Issue by pstolpe** [inverse-inc/packetfence#5384]
The unregistration of an autoregistered device does not work when an autoregistered 802.1x user switch to an Open SSID.

In the file:
conf/vlan_filters.conf.defaults

In PF 9.3 the cases handled by the default file was from both wired and wireless EAP but in the lastest version it looks like its only from wired EAP to Wireless.

We switch from node_info.last_connection_type == "Wireless-802.11-EAP" too and not only Ethernet-EAP.

I have tried to change the default file to the condition below but the logic doesn't seem to work as expected.

condition=connection_type == "Wireless-802.11-NoEAP" && node_info.last_connection_type == "Wireless-802.11-EAP" && node_info.status == "reg" && node_info.autoreg == "yes"

**Comment by julsemaan** [comment]
The issues with this VLAN filter have been addressed yesterday in the maintenance by 139e01e5ed480622eea9e9058df602a8ae7a9e00 and 0e6549c704b26fc1f372ccc5b936011777655af1

You can obtain the fixes by running:
```
/usr/local/pf/addons/pf-maint.pl
/usr/local/pf/bin/pfcmd service pf restart
```

**Comment by pstolpe** [comment]
I did update and restart but it still doesn't work as expected.
The node still get the VLAN from autoreg profile.

**Comment by julsemaan** [comment]
This filter can only handle the first transition. That means you'll have to connect again to the 802.1x SSID, then back to the open for the mechanism to trigger properly.

If that still doesn't work, try reloading the config too:
```
/usr/local/pf/bin/pfcmd configreload hard
```

**Comment by pstolpe** [comment]
Hi I did the hard configreload and I did restart the server but still have the same problems. As if the rule does not hit at all.

**Comment by julsemaan** [comment]
Did you also take into consideration the first part of my comment:

> This filter can only handle the first transition. That means you'll have to connect again to the 802.1x SSID, then back to the open for the mechanism to trigger properly.

**Comment by pstolpe** [comment]
Hi, yes I did take that into consideration.

    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] handling radius autz request: from switch_ip => (XXX.XXX.XXX.XXX), connection_type => Wireless-802.11-EAP,switch_mac => (70:10:5c:35:a4:70), mac => [28:18:78:57:d8:b1], port => 8, username => "anonymous@test.liu.se", ssid => maurode (pf::radius::authorize)
    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Instantiate profile eduroam (pf::Connection::ProfileFactory::_from_profile)
    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Found authentication source(s) : 'roamer-d' for realm 'default' (pf::config::util::filter_authentication_sources)
    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Using sources roamer-d for matching (pf::authentication::match2)
    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Matched rule (test.liu.se) in source roamer-d, returning actions. (pf::Authentication::Source::match_rule)
    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Matched rule (test.liu.se) in source roamer-d, returning actions. (pf::Authentication::Source::match)
    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Found authentication source(s) : 'roamer-d' for realm 'default' (pf::config::util::filter_authentication_sources)
    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Role has already been computed and we don't want to recompute it. Getting role from node_info (pf::role::getRegisteredRole)
    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Username was defined "anonymous@test.liu.se" - returning role 'ifm-twilight' (pf::role::getRegisteredRole)
    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] PID: "anonymous@test.liu.se", Status: reg Returned VLAN: (undefined), Role: ifm-twilight (pf::role::fetchRoleForNode)
    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] (XXX.XXX.XXX.XXX) Added VLAN 2068 to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)
    Apr 24 16:04:38 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Instantiate profile eduroam (pf::Connection::ProfileFactory::_from_profile)
    
    
    Apr 24 16:05:21 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] handling radius autz request: from switch_ip => (XXX.XXX.XXX.XXX), connection_type => Wireless-802.11-NoEAP,switch_mac => (70:10:5c:35:a4:70), mac => [28:18:78:57:d8:b1], port => 8, username => "28187857d8b1", ssid => guest (pf::radius::authorize)
    Apr 24 16:05:21 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Instantiate profile liu (pf::Connection::ProfileFactory::_from_profile)
    Apr 24 16:05:21 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Found authentication source(s) : 'local,file1,roamer-d' for realm 'null' (pf::config::util::filter_authentication_sources)
    Apr 24 16:05:21 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Connection type is MAC-AUTH. Getting role from node_info (pf::role::getRegisteredRole)
    Apr 24 16:05:21 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] Username was defined "28187857d8b1" - returning role 'ifm-twilight' (pf::role::getRegisteredRole)
    Apr 24 16:05:21 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] PID: "anonymous@test.liu.se", Status: reg Returned VLAN: (undefined), Role: ifm-twilight (pf::role::fetchRoleForNode)
    Apr 24 16:05:21 nix00 packetfence_httpd.aaa: httpd.aaa(51106) INFO: [mac:28:18:78:57:d8:b1] (XXX.XXX.XXX.XXX) Added VLAN 2068 to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)
    
    +-------------------+---------------------+--------+--------------+---------+
    | mac               | regdate             | status | computername | autoreg |
    +-------------------+---------------------+--------+--------------+---------+
    | 28:18:78:57:d8:b1 | 2020-04-24 16:04:38 | reg    | Fenix        | yes     |
    +-------------------+---------------------+--------+--------------+---------+

**Comment by julsemaan** [comment]
We were able to replicate this issue in our lab and you're right, the filter as it was in the defaults didn't work even with the fixes.

I pushed another fix to the maintenance. Can you do:
```
/usr/local/pf/addons/pf-maint.pl
/usr/local/pf/bin/pfcmd configreload hard
/usr/local/pf/bin/pfcmd service pf restart
```

And then try again

**Comment by pstolpe** [comment]
Thanks for the prompt fix, I have just now confirmed that it works as intended.
