### ISSUE TITLE
Unit tests: issue on latest builds

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5489]
**Describe the bug**
Latest builds report issues on unit tests

https://gitlab.com/inverse-inc/packetfence/-/jobs/574011297#L741

**Comment by jrouzierinverse** [comment]
Fixed by
79d2c940386a2400c0dcdbc3111d45e19f7d433d
3b04da55bca0aaa8a54d71f604408ba82bdb2046

**Comment by nqb** [comment]
Errors are still present: https://gitlab.com/inverse-inc/packetfence/-/jobs/575461955#L544

**Comment by jrouzierinverse** [comment]
I have to dig a bit deeper since that test works on my environment
