### ISSUE TITLE
Searching RADIUS attributes doesn't work on 10.0 maintenance

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5882]
**Describe the bug**
Searching for RADIUS attributes in the RADIUS filter section doesn't work and prevents you from finding the attribute you want to use to setup the answer.

**To Reproduce**
1. Be on maintenance/10.0 commit ID ab186720ca506ff8b7b9fcd2c63b688eed29e69a
2. `curl 'https://localhost:9999/api/v1/radius_attributes' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en' --compressed -H 'Authorization: Bearer f60f99faeb6276ac0002ecb54aae861f31eab45bfe5ed5ba4a441c186baf917f'  -d '{"query":{"op":"and","values":[{"op":"or","values":[{"field":"name","op":"contains","value":"timeout"}]}]},"fields":["name","name"],"sort":["name"],"cursor":0,"limit":100}' -k | python -m json.tool | less`

**Comment by jrouzierinverse** [comment]
This has been fixed by b1b43a737c69578ff2cf18e6b20d65256c7d48d1

**Comment by julsemaan** [comment]
This is still broken, I applied the latest maintenance and searching for idle-timeout yields the following response:
```
[root@vPF1 pf]# curl 'https://localhost:9999/api/v1/radius_attributes' -H 'User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en' --compressed -H 'Authorization: Bearer 5fee48725319adcaabefb539df77853071c7daa193fc55041262b2353cda9dca' -d '{"query":{"op":"and","values":[{"op":"or","values":[{"field":"name","op":"contains","value":"idle-timeout"}]}]},"fields":["name","name"],"sort":["name"],"cursor":0,"limit":100}' -k | python -m json.tool | less
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   203  100    27  100   176    220   1438 --:--:-- --:--:-- --:--:--  1442
{
    "message": "",
    "status": 200
}
```

**Comment by julsemaan** [comment]
searching for `timeout` now works but not `Idle-Timeout`.

Interesting thing to note, searching for `timeout` doesn't yield the `Idle-Timeout` attribute

**Comment by julsemaan** [comment]
@jrouzierinverse, can you take a look into this? I have a customer waiting for the fix

**Comment by jrouzierinverse** [comment]
The search is case sensitive.

**Comment by jrouzierinverse** [comment]
Has been fixed by 3b05595e5635633142e39490392516a4706b1225
