### ISSUE TITLE
Access Duration not Working on PacketFence Configuration

### ISSUE THREAD

**Issue by vezeh** [inverse-inc/packetfence#6117]
Hi,

I have successfully configured PacketFence with Cisco WLC using the captive portal to provision Sponsor-based access for Guests.

When guests login to sponsor access, they are provided with the options for different access durations as configured within the Connection Profile referencing the connection for the guest.

But the selection of the desired access duration does not apply to the guest and the guest receives an un-registration date as determined by the packetfence application.

For a better understanding;

**What is happening right now:**

- When a guest requests for access through the portal; 
the sponsor receives an email to grant access. 

- Once the sponsor authenticates to grant access, the sponsor is presented with some options of duration that can be assigned to the guest. 

- The sponsor selects an option from the list of duration on the portal, the guest's device is then registered and granted access. 

- When information of the user is verified, it is noticed that the un-registration date for the user does not correlate with the duration selected by the sponsor during the process of granting the guest access on the portal.

**WorkFlow Needed:**
- A guest requests for access via the portal,
a sponsor receives the email, authenticates and grants access to the guest for a specified duration based on the options presented to the sponsor on the portal. 

- The device of the guest is then registered and granted access to the internet for the duration specified by the sponsor. 

- Once the duration elapses, the device is automatically unregistered and internet access is retrieved.

**Explanation of the configuration**

![image](https://user-images.githubusercontent.com/31307477/106167807-e67a7480-618d-11eb-8b65-3e61d286a271.png)

When I connect, I actually reference the right profile
![image](https://user-images.githubusercontent.com/31307477/106167910-feea8f00-618d-11eb-9113-3e9c10094260.png)

Within the Authentication Sources, this configuration has been done
![image](https://user-images.githubusercontent.com/31307477/106167995-1590e600-618e-11eb-8d3d-6f3cfb127779.png)

The various selections are available for sponsors to select from
![image](https://user-images.githubusercontent.com/31307477/106168066-29d4e300-618e-11eb-8728-090bf56edabb.png)

After a user has been granted access for 2 minutes, this is what it correlates to when verified under the information for user
![image](https://user-images.githubusercontent.com/31307477/106168180-4709b180-618e-11eb-9142-7659dfbf488e.png)

This test was carried out on 14th January 2021 and the session was set to expire 16th January 2021. 2 days later

It seems this is a bug, can anyone assist to rectify this?

**Comment by vezeh** [comment]
This test was carried out on 14th January 2021 and the session was set to expire 16th January 2021. 2 days later

**Comment by julsemaan** [comment]
I guess we'll have to test that case in lab on our end.

Please post the following files:
```
/usr/local/pf/conf/authentication.conf
/usr/local/pf/conf/profiles.conf
```

Ensure you strip any sensitive information from the files before posting them here

**Comment by vezeh** [comment]
@julsemaan 

Find the files below;
** /usr/local/pf/conf/authentication.conf**

# Copyright (C) Inverse inc.
[local]
description=Local Users
type=SQL

[file1]
description=Legacy Source
path=/usr/local/pf/conf/admin.conf
type=Htpasswd
realms=null

[file1 rule admins]
description=All admins
class=administration
match=all
action0=set_access_level=ALL
status=enabled

[sms]
description=SMS-based registration
sms_carriers=100056,100057,100061,100058,100059,100060,100062,100063,100071,100064,100116,100066,100117,100112,100067,100065,100068,100069,100070,100118,100115,100072,100073,100074,100075,100076,100077,100085,100086,100080,100079,100081,100083,100082,100084,100087,100088,100111,100089,100090,100091,100092,100093,100094,100095,100096,100098,100097,100099,100100,100101,100113,100102,100103,100104,100106,100105,100107,100108,100109,100114,100110,100078,100119,100120,100121,100122,100123,100124,100125,100126,100127,100128
type=SMS
create_local_account=no

[sms rule catchall]
description=
class=authentication
match=all
action0=set_role=guest
action1=set_access_duration=1D
status=enabled

[email]
description=Email-based registration
email_activation_timeout=10m
type=Email
allow_localdomain=yes
create_local_account=no

[email rule catchall]
description=
class=authentication
match=all
action0=set_role=guest
action1=set_access_duration=1D
status=enabled

[sponsor]
description=Sponsor-based registration
type=SponsorEmail
allow_localdomain=no
create_local_account=no
validate_sponsor=yes
password_length=8
set_access_durations_action=
lang=en_US
banned_domains=*dangote.com,*gmail.com,*yahoo.com,*yahoomail.com,*msn.com,*hotmail.com,*outlook.com,*yahoo.co.uk,*yahoo.co.in,*rocketmail.com
local_account_logins=0
email_activation_timeout=30m
sources=Dangote-Staff
hash_passwords=bcrypt
register_on_activation=enabled

[sponsor rule catchall]
action0=set_access_duration=12h
status=enabled
match=all
class=authentication
action1=set_role=guest

[null]
description=Null Source
type=Null
email_required=no

[null rule catchall]
description=catchall
class=authentication
match=all
action0=set_role=guest
action1=set_access_duration=1D
status=enabled

[Dangote-Staff]
cache_match=0
read_timeout=10
realms=
basedn=dc=xxxxxxxx,dc=xxxxxxxx
monitor=1
password=xxxxx
shuffle=1
searchattributes=UserPrincipalName
set_access_durations_action=
scope=sub
email_attribute=mail
usernameattribute=sAMAccountName
connection_timeout=1
binddn=CN=xxxxxxx,CN=xxxxx,DC=xxxxxxx,DC=xxxxxx
encryption=none
description=All-Staff
port=389
host=xx.xx.xx.xx,xx.xx.xx.xx,xx.xx.xx.xx
write_timeout=5
type=LDAP

[Dangote-Staff rule catchall1]
action0=mark_as_sponsor=1
condition0=memberOf,equals,CN=VIPs,OU=Groups,DC=DANGOTE-GROUP,DC=com
status=enabled
match=all
class=administration
action1=set_access_durations=2m,12h,40h,2W,1M

[POTD rule catchall]
action0=set_role=guest
status=enabled
match=all
class=authentication
action1=set_access_duration=12h



**/usr/local/pf/conf/profiles.conf**

# Copyright (C) Inverse inc.
[general]
#
# general.domain
#
# Domain name of PacketFence system.
domain=xxxxxxxx
#
# general.hostname
#
# Hostname of PacketFence system.  This is concatenated with the domain in Apache rewriting rules and therefore must be resolvable by clients.
hostname=ikjdc-prd-pkf01
#
# general.timezone
#
# System's timezone in string format. List generated from Perl library DateTime::TimeZone
# When left empty, it will use the timezone of the server
timezone=Africa/Lagos

[guests_admin_registration]
#
# guests_admin_registration.access_duration_choices
#
# These are all the choices offered in the guest management interface as 
# possible access duration values for a given registration.
access_duration_choices=12h,40h,2W,1M,2m

[alerting]
#
# alerting.fromaddr
#
# Source email address for email notifications. Empty means root@<server-domain-name>.
fromaddr=xxxxxxxxx
#
# alerting.smtpserver
#
# Server through which to send messages to the above emailaddr.  The default is localhost - be sure you're running an SMTP 
# host locally if you don't change it!
smtpserver=xxxxxxx
#
# alerting.subjectprefix
#
#Subject prefix for email notifications of rogue DHCP servers, security_events with an action of "email", or any other
#PacketFence-related message.
subjectprefix=Guest-Wireless Alert: Guest-Access Request

[database]
#
# database.pass
#
# Password for the mysql database used by PacketFence. Changing this parameter after the initial configuration will *not* change it in the database it self, only in the configuration.
pass=xxxxxxxx

[advanced]
# advanced.configurator
#
# Enable the Configurator and the Configurator API
configurator=disabled

[interface eth0]
ip=xxxxxxx
type=management,portal,radius
mask=255.255.255.0

**Comment by vezeh** [comment]
@julsemaan 

Find both files below

[authentication.conf.txt](https://github.com/inverse-inc/packetfence/files/5892667/authentication.conf.txt)
[pf.conf.txt](https://github.com/inverse-inc/packetfence/files/5892669/pf.conf.txt)

**Comment by julsemaan** [comment]
This seems to be because the access duration you pick while enabling the access of the sponsor is not honored when register_on_activation is enabled in the sponsor source.

I'll try to get a fix going for this, you can always disable that feature in the meanwhile to see if that works for you.
Note that without this feature enabled, the user must stay on the portal until the sponsor has granted him access.

**Comment by julsemaan** [comment]
This has been fixed, you can apply the maintenance patches using:
```
/usr/local/pf/addons/pf-maint.pl
/usr/local/pf/bin/pfcmd service pf restart
```

**Comment by vezeh** [comment]
@julsemaan 

Please note that I have applied the maintenance patch long before this and the issue still persists.

I will try out your other recommendation and revert.

Please do not close the issue yet.

**Comment by julsemaan** [comment]
I pushed a fix for this, that's why I'm saying that its in the maintenance branch, see the commit listed in that issue

**Comment by vezeh** [comment]
Thank you @julsemaan, the issue has been resolved.
